#!/usr/bin/env bash
#
# Build, sign, push, and apply the DNS-node closures.
#
# Builds both dns-usw2 + dns-use2 system toplevels via nixbuild.net (configured
# as a remote builder on the operator workstation), signs and uploads each to
# the s3://burk3-dns-cache bucket using the operator's local signing key, then
# writes the resulting store paths into terraform/paths.auto.tfvars (gitignored)
# and runs `terraform apply` which forces instance replacement so user-data
# re-runs with the new path baked in.
#
# Requirements:
# - In `nix develop` (terraform + awscli2 + jq on PATH)
# - AWS_PROFILE=tactilecactus (or otherwise have AWS credentials)
# - NIX_CACHE_SECRET_KEY pointing at the cache signing key file
#     (default: ~/.config/nix-cache/burk3-dns-cache.secret)
#
# Usage:
#   ./scripts/deploy-dns.sh
#   ./scripts/deploy-dns.sh --skip-apply        # build + push only, no terraform
set -euo pipefail

NIX_CACHE_SECRET_KEY="${NIX_CACHE_SECRET_KEY:-$HOME/.config/nix-cache/burk3-dns-cache.secret}"
AWS_PROFILE="${AWS_PROFILE:-tactilecactus}"
BUCKET="${BUCKET:-burk3-dns-cache}"
BUCKET_REGION="${BUCKET_REGION:-us-west-2}"

SKIP_APPLY=0
for arg in "$@"; do
  case "$arg" in
    --skip-apply) SKIP_APPLY=1 ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

if [ ! -r "$NIX_CACHE_SECRET_KEY" ]; then
  echo "error: signing key not readable: $NIX_CACHE_SECRET_KEY" >&2
  echo "set NIX_CACHE_SECRET_KEY env var if it lives elsewhere" >&2
  exit 1
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

echo "==> Building dns-usw2 + dns-use2 toplevels (aarch64-linux via nixbuild.net)"
nix build --no-link --print-build-logs \
  .#nixosConfigurations.dns-usw2.config.system.build.toplevel \
  .#nixosConfigurations.dns-use2.config.system.build.toplevel

USW2=$(nix eval --raw .#nixosConfigurations.dns-usw2.config.system.build.toplevel)
USE2=$(nix eval --raw .#nixosConfigurations.dns-use2.config.system.build.toplevel)

echo "dns-usw2 toplevel: $USW2"
echo "dns-use2 toplevel: $USE2"

echo "==> Signing + pushing closures to s3://$BUCKET"
export AWS_PROFILE
# `nix copy --to` resolves AWS creds via the AWS credential provider chain
# (env, profile, IMDS, ~/.aws/credentials). It reads the local store paths
# and uploads the .narinfo + .nar.xz parts, signing on the way out.
SUBSTITUTER_TO="s3://${BUCKET}?region=${BUCKET_REGION}&secret-key=${NIX_CACHE_SECRET_KEY}"
nix copy --to "$SUBSTITUTER_TO" "$USW2"
nix copy --to "$SUBSTITUTER_TO" "$USE2"

echo "==> Writing terraform/paths.auto.tfvars"
cat > terraform/paths.auto.tfvars <<EOF
# Auto-generated by scripts/deploy-dns.sh. Do not edit.
dns_usw2_toplevel_path = "${USW2}"
dns_use2_toplevel_path = "${USE2}"
EOF

if [ "$SKIP_APPLY" -eq 1 ]; then
  echo "==> --skip-apply set; stopping before terraform"
  exit 0
fi

echo "==> Running terraform apply"
cd terraform
terraform apply -auto-approve
